server:
  port: 8090
  
spring:
  datasource:
    url: jdbc:h2:file:./geicodb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
jwt:
  decryptKey: test   
  